### ISSUE TITLE
[sandbox]ray not available in python 3.6.7

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-build#16]
## Reproduce
ray not available in python 3.6.7！

When I run the code executed by the `ray` cluster, I get the following error.

```
org.apache.spark.sql.mlsql.session.MLSQLException: An exception was encountered in the execution of this python task! Please check your code and try again after modification.

at tech.mlsql.ets.Ray.distribute_execute(Ray.scala:191)

at tech.mlsql.ets.Ray.train(Ray.scala:56)

at tech.mlsql.dsl.adaptor.TrainAdaptor.parse(TrainAdaptor.scala:116)

at streaming.dsl.ScriptSQLExecListener.execute$1(ScriptSQLExec.scala:408)

at streaming.dsl.ScriptSQLExecListener.exitSql(ScriptSQLExec.scala:447)

at streaming.dsl.parser.DSLSQLParser$SqlContext.exitRule(DSLSQLParser.java:296)

at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)

at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)

at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)

at streaming.dsl.ScriptSQLExec$._parse(ScriptSQLExec.scala:160)

at streaming.dsl.ScriptSQLExec$.parse(ScriptSQLExec.scala:147)

at streaming.rest.RestController.$anonfun$script$1(RestController.scala:153)

at tech.mlsql.job.JobManager$.run(JobManager.scala:74)

at tech.mlsql.job.JobManager$$anon$1.run(JobManager.scala:91)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

Caused by: org.apache.spark.SparkException: Traceback (most recent call last):

  File "/opt/conda/envs/ray1.8.0/lib/python3.6/site-packages/pyjava/worker.py", line 155, in main

    process()

  File "/opt/conda/envs/ray1.8.0/lib/python3.6/site-packages/pyjava/worker.py", line 132, in process

    exec(code, n_local, n_local)

  File "<string>", line 5, in <module>

  File "/opt/conda/envs/ray1.8.0/lib/python3.6/site-packages/pyjava/api/mlsql.py", line 263, in connect

    ray.init(url, **kwargs)

  File "/opt/conda/envs/ray1.8.0/lib/python3.6/site-packages/pyjava/rayfix.py", line 33, in init

    ray.util.connect(conn_str=address, namespace="default", **kwargs)

  File "/opt/conda/envs/ray1.8.0/lib/python3.6/site-packages/ray/util/client_connect.py", line 42, in connect

    ray_init_kwargs=ray_init_kwargs)

  File "/opt/conda/envs/ray1.8.0/lib/python3.6/site-packages/ray/util/client/__init__.py", line 221, in connect

    conn = self.get_context().connect(*args, **kw_args)

  File "/opt/conda/envs/ray1.8.0/lib/python3.6/site-packages/ray/util/client/__init__.py", line 81, in connect

    self.client_worker._server_init(job_config, ray_init_kwargs)

  File "/opt/conda/envs/ray1.8.0/lib/python3.6/site-packages/ray/util/client/worker.py", line 699, in _server_init

    f"Initialization failure from server:\n{response.msg}")

ConnectionAbortedError: Initialization failure from server:

Call to `ray.init()` on the server failed with: can't pickle function objects


at tech.mlsql.arrow.python.runner.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:324)

at tech.mlsql.arrow.python.runner.ArrowPythonRunner$$anon$2.read(ArrowPythonRunner.scala:154)

at tech.mlsql.arrow.python.runner.ArrowPythonRunner$$anon$2.read(ArrowPythonRunner.scala:151)

at tech.mlsql.arrow.python.runner.ArrowPythonRunner$$anon$2.read(ArrowPythonRunner.scala:102)

at tech.mlsql.arrow.python.runner.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:293)

at tech.mlsql.arrow.python.runner.InterruptibleIterator.hasNext(PythonRunner.scala:415)

at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)

at scala.collection.Iterator.foreach(Iterator.scala:941)

at scala.collection.Iterator.foreach$(Iterator.scala:941)

at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)

at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)

at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)

at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)

at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)

at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)

at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)

at scala.collection.AbstractIterator.to(Iterator.scala:1429)

at scala.collection.TraversableOnce.toList(TraversableOnce.scala:299)

at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:299)

at scala.collection.AbstractIterator.toList(Iterator.scala:1429)

at tech.mlsql.ets.Ray.distribute_execute(Ray.scala:181)

... 16 more
```

**Comment by hellozepp** [comment]
This bug is mentioned in the ray issues, and it seems that upgrading to python3.7.10 can solve this problem.

[ray issue 19938](https://github.com/ray-project/ray/issues/19938)

**Comment by hellozepp** [comment]
# #17
